---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: user-profile
  name: user-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-profile
    spec:
      containers:
      - image: registryosu7731.azurecr.io/user-profile:latest
        name: user-profile
        ports:
          - containerPort: 80
        envFrom:
        - secretRef:
            name: sql-credentials
        resources: {}
status: {}
...
