---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: user-java
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-java
    spec:
      containers:
      - image: registryosu7731.azurecr.io/user-java:latest
        name: user-java
        resources: {}
status: {}
...
