---
apiVersion: v1
kind: Secret
metadata:
  name: sql-credentials
data:
  SQL_PASSWORD: dVg2eWw4QW03
  SQL_SERVER: c3Fsc2VydmVyb3N1NzczMS5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  SQL_USER: c3FsYWRtaW5vU3U3NzMx
...
